# The file is configured by default for a Linux build
# Specifications for Windows & OSX are done per-job
language: python
dist: bionic
cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
      - libproj-dev
      - proj-data
      - proj-bin
      - libgeos-dev
      - libopenmpi-dev

env:
  global:
    PIP=pip
    HOMEBREW_NO_AUTO_UPDATE=1

before_install:
  - source tests/travis_before_install.sh

install:
  - source tests/travis_install.sh

jobs:
  include:
    - stage: tests
      name: "MacOS: Unit Tests"
      os: osx
      osx_image: xcode10.1
      language: shell
      env: PIP=pip3
      cache:
        - directories:
          - $HOME/Library/Caches/pip
      script: pytest -c pytest_unit.ini
      name: "MacOS: Unit Tests"
      os: osx
      osx_image: xcode10.1
      language: shell
      env: PIP=pip3
      cache:
        - directories:
          - $HOME/Library/Caches/pip
      script: pytest -c pytest_unit.ini

    - stage: tests
      name: "Windows: Unit Tests"
      os: windows
      language: shell
      script: coverage run -m pytest -c pytest_unit.ini
      cache:
          directories:
          - /c/miniconda/pkgs
          - $HOME/AppData/Local/Temp/chocolatey
          - $HOME/AppData/Local/pip
          - $HOME/AppData/Local/conda/conda/pkgs
          - $HOME/.conda/pkgs

    - stage: tests
      name: "Python: 3.6 Minimal Dependency Unit Tests"
      python: 3.6
      env: MINIMAL=1
      script: coverage run $(which pytest) -c pytest_unit.ini

    - stage: tests
      name: "Python: 3.6 Unit Tests"
      python: 3.6
      script: coverage run $(which pytest) -c pytest_unit.ini

    - stage: tests
      name: "Python: 3.8 Unit Tests"
      python: 3.8
      script: coverage run $(which pytest) -c pytest_unit.ini

    - stage: tests
      name: "Python: 3.7 Answer Tests"
      python: 3.7
      script: coverage run $(which pytest) -c pytest_answer.ini
      # This script has not yet been converted to use pytest, so skip for now
      # after_failure: python tests/report_failed_answers.py -f -m --xunit-file "answer_pytest.xml"

after_success:
  - codecov

