# This is a dummy configuration file that *does not run any test*.
# The file should be deleted, and Appveyor deactivated as soon as all
# opened PRs have this configuration merged in.
# SEE PR#2908 (https://github.com/yt-project/yt/pull/2908/files)

platform:
    - x64

install:
    - "echo 'Not installing anything.'"

build: false

test_script:
    - "echo 'Not testing anything. This is done on Travis'"
